import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const pkgRoot = join(__dirname, '..');
const srcDir = join(pkgRoot, 'src');
const distDir = join(pkgRoot, 'dist');

// Helper to deep merge objects
function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      if (!target[key] || typeof target[key] !== 'object') {
        target[key] = {};
      }
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

// Helper to load all json files from a folder recursively
async function loadJsonFromDir(dirPath) {
  let combined = {};
  try {
    const entries = await readdir(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dirPath, entry.name);
      if (entry.isDirectory()) {
        const sub = await loadJsonFromDir(fullPath);
        deepMerge(combined, sub);
      } else if (entry.name.endsWith('.json')) {
        const content = JSON.parse(await readFile(fullPath, 'utf-8'));
        deepMerge(combined, content);
      }
    }
  } catch (err) {
    // ignore if directory doesn't exist
  }
  return combined;
}

// Load base primitives, semantic, components
const primitives = await loadJsonFromDir(join(srcDir, 'primitives'));
const semantic = await loadJsonFromDir(join(srcDir, 'semantic'));
const components = await loadJsonFromDir(join(srcDir, 'components'));

const baseTokens = {};
deepMerge(baseTokens, primitives);
deepMerge(baseTokens, semantic);
deepMerge(baseTokens, components);

// Read themes
const themeFiles = await readdir(join(srcDir, 'themes'));
const cssThemeBlocks = [];
const themesMetadata = [];

for (const themeFile of themeFiles) {
  if (!themeFile.endsWith('.json')) continue;
  const themePath = join(srcDir, 'themes', themeFile);
  const themeConfig = JSON.parse(await readFile(themePath, 'utf-8'));
  
  // Clone base and apply overrides
  const themeTokens = JSON.parse(JSON.stringify(baseTokens));
  if (themeConfig.overrides) {
    deepMerge(themeTokens, themeConfig.overrides);
  }

  // Flatten theme tokens
  const flat = {};
  const walk = (node, path = []) => {
    if (!node || typeof node !== 'object') return;
    if ('$value' in node) {
      flat[path.join('.')] = node.$value;
    } else {
      for (const [key, value] of Object.entries(node)) {
        walk(value, path.concat(key));
      }
    }
  };
  walk(themeTokens);

  // Alias resolution
  const resolveValue = (value) => {
    if (typeof value !== 'string') return value;
    let current = value;
    let maxDepth = 10;
    while (typeof current === 'string' && current.includes('{') && maxDepth > 0) {
      current = current.replace(/\{([^}]+)\}/g, (_, aliasKey) => {
        return flat[aliasKey] ?? _;
      });
      maxDepth--;
    }
    return current;
  };

  const cssVars = Object.entries(flat).map(([key, rawVal]) => {
    const resolved = resolveValue(rawVal);
    const varName = `--${key.replaceAll('.', '-')}`;
    return `  ${varName}: ${resolved};`;
  });

  const selector = themeConfig.selector || `[data-theme="${themeConfig.name}"]`;
  cssThemeBlocks.push(`/* Theme: ${themeConfig.name} */\n${selector} {\n${cssVars.join('\n')}\n}`);
  themesMetadata.push(themeConfig.name);
}

// Clean and recreate dist
await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });

// Write dist/tokens.css
const cssHeader = `/* Generated by @enterprise/design-tokens build script. Do not edit directly. */\n\n`;
await writeFile(join(distDir, 'tokens.css'), cssHeader + cssThemeBlocks.join('\n\n') + '\n');

// Write dist/index.js
const jsContent = `// Generated by @enterprise/design-tokens build script
export const tokenPackage = '@enterprise/design-tokens';
export const availableThemes = ${JSON.stringify(themesMetadata, null, 2)};
`;
await writeFile(join(distDir, 'index.js'), jsContent);

// Write dist/index.d.ts
const dtsContent = `// Generated by @enterprise/design-tokens build script
export declare const tokenPackage: string;
export declare const availableThemes: readonly string[];
`;
await writeFile(join(distDir, 'index.d.ts'), dtsContent);

console.log(`Successfully built @enterprise/design-tokens (${themesMetadata.length} themes generated).`);
